### ISSUE TITLE
华为matexs用户报告问题

### ISSUE THREAD

**Issue by zhangyiming748** [rLingMX/pwl-chat-uniapp#1]
![Screenshot_20211223_151045_pwl.chat.jpg](https://user-images.githubusercontent.com/37614800/147202669-5a0907c5-c063-4a71-89cf-98ca64a66441.jpg)
无法显示文字内容

**Comment by HereIsYui** [comment]
请问手机系统是安卓11还是鸿蒙

**Comment by zhangyiming748** [comment]
> 请问手机系统是安卓11还是鸿蒙

安卓10 EMUI11，并且华为没有安卓11授权 也没有ARMv8授权 只有魔改ARMv7a

**Comment by HereIsYui** [comment]
目前有多个机型出现了该问题，正在排查原因

<html>
<body>


|机型 | 系统 | 问题描述|
|-- | -- | --|
|红米 K40 | 安卓11 | 聊天内容看不到，对话框可输入消息不能发送，下面的3个点击没反应|
|小米 11 | 安卓11 | 同上|
|小米 10 | 安卓11 | 同上|
|oppo  | 安卓11 | 同上|
|荣耀magic2 | HarmonyOS 2 | 同上|

**Comment by HereIsYui** [comment]
已更新V0.0.3 麻烦试试是否可用 https://github.com/rLingMX/pwl-chat-uniapp/releases/tag/beta.3

**Comment by zhangyiming748** [comment]
> 已更新V0.0.3 麻烦试试是否可用 https://github.com/rLingMX/pwl-chat-uniapp/releases/tag/beta.3

已经可以正常使用了 收发文字消息、图片都正常
