### ISSUE TITLE
手机端只能显示大约20条历史信息

### ISSUE THREAD

**Issue by zhangyiming748** [rLingMX/pwl-chat-uniapp#3]
向上划最多20条历史消息
如果有人发送复读机消息
基本上看不见之前的任何消息
老板可以尝试把limit调大一点

**Comment by HereIsYui** [comment]
我在添加加载历史消息和复读折叠功能~~

**Comment by zhangyiming748** [comment]
> 我在添加加载历史消息和复读折叠功能~~

谢谢老板
